DROP TABLE IF EXISTS DEVICE;

CREATE TABLE DEVICE  (
	USERNAME VARCHAR(250) NOT NULL ,
	USERID VARCHAR(250) NOT NULL ,
	DEVICENAME VARCHAR(250) NOT NULL ,
	DATETIME VARCHAR(250) NOT NULL ,
	PARAMETER VARCHAR(250) NOT NULL ,
	METRICVALUE VARCHAR(250) NOT NULL ,
	LOCATION VARCHAR(250) NOT NULL 
	
)